# Generated by Django 5.2.5 on 2025-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('tasks', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('clients', models.CharField(blank=True, max_length=255, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_stack', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-date'],
            },
        ),
    ]
